'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const supabase=createClient('https://sdbdppcbvlalyjnxeqmy.supabase.co','sb_publishable_YRnoxe5WTODYiA67nLfpNg_JqYHdaYM');

function Donut({value,total,label,color}:{value:number,total:number,label:string,color:string}){const pct=total?Math.round(value/total*100):0;const r=44,c=2*Math.PI*r,dash=c*pct/100;return <div className='viz-donut-wrap'><svg viewBox='0 0 120 120' className='viz-donut'><circle cx='60' cy='60' r={r} className='viz-ring-bg'/><circle cx='60' cy='60' r={r} fill='none' stroke={color} strokeWidth='12' strokeLinecap='round' strokeDasharray={`${dash} ${c-dash}`} transform='rotate(-90 60 60)'/><text x='60' y='57' textAnchor='middle' className='viz-donut-number'>{pct}%</text><text x='60' y='76' textAnchor='middle' className='viz-donut-small'>{value}/{total}</text></svg><div className='viz-donut-label'>{label}</div></div>}
function Bars({rows}:{rows:{label:string,value:number,color:string}[]}){const max=Math.max(1,...rows.map(x=>x.value));return <div className='viz-bars'>{rows.map((r,i)=><div className='viz-bar-row' key={i}><div className='viz-bar-label'><span>{r.label}</span><strong>{r.value}</strong></div><div className='viz-bar-track'><div className='viz-bar-fill' style={{width:`${r.value?Math.max(3,r.value/max*100):0}%`,background:r.color}}/></div></div>)}</div>}

export default function CommandCenter(){
 const [lang,setLang]=useState<'en'|'ar'>('en'),[loading,setLoading]=useState(true),[profile,setProfile]=useState<any>(null),[d,setD]=useState<any>({});
 const t=(en:string,ar:string)=>lang==='ar'?ar:en;const n=(v:any)=>new Intl.NumberFormat(lang==='ar'?'ar-EG':'en-US').format(Number(v||0));
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/';return}const {data:p}=await supabase.from('profiles').select('*').eq('id',session.user.id).single();setProfile(p);const tables=['incidents','work_orders','physical_security_records','agriculture_checklists','ppm_schedules','assets','inspections','risks','corrective_actions','agriculture_followups','contracts','notifications','security_patrols','emergency_events','digital_form_records'];const res=await Promise.all(tables.map(x=>supabase.from(x).select('*').limit(500)));const o:any={};tables.forEach((x,i)=>o[x]=res[i].data||[]);setD(o);setLoading(false)})()},[]);
 useEffect(()=>{document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.documentElement.lang=lang},[lang]);
 const s=useMemo(()=>{const inc=d.incidents||[],wo=d.work_orders||[],ag=d.agriculture_checklists||[],ppm=d.ppm_schedules||[],risk=d.risks||[],ca=d.corrective_actions||[],insp=d.inspections||[],fu=d.agriculture_followups||[],contracts=d.contracts||[],emg=d.emergency_events||[],pat=d.security_patrols||[];return{incOpen:inc.filter((x:any)=>x.status!=='closed').length,incCritical:inc.filter((x:any)=>['high','critical'].includes((x.severity||'').toLowerCase())).length,woOpen:wo.filter((x:any)=>!['completed','cancelled'].includes(x.workflow_status)).length,woOver:wo.filter((x:any)=>x.overdue).length,woDone:wo.filter((x:any)=>x.workflow_status==='completed').length,agDone:ag.filter((x:any)=>x.status==='completed').length,ppmActive:ppm.filter((x:any)=>x.active).length,riskOpen:risk.filter((x:any)=>x.status!=='closed').length,riskHC:risk.filter((x:any)=>['high','critical'].includes((x.risk_level||'').toLowerCase())).length,caOpen:ca.filter((x:any)=>!['completed','cancelled'].includes(x.status)).length,inspDone:insp.filter((x:any)=>x.status==='completed').length,fuOpen:fu.filter((x:any)=>!['completed','cancelled'].includes(x.status)).length,contracts60:contracts.filter((x:any)=>x.status==='active'&&x.end_date&&new Date(x.end_date).getTime()-Date.now()<=60*86400000&&new Date(x.end_date).getTime()>=Date.now()).length,emgOpen:emg.filter((x:any)=>x.status!=='closed').length,emgCritical:emg.filter((x:any)=>['high','critical'].includes((x.severity||'').toLowerCase())&&x.status!=='closed').length,patCritical:pat.filter((x:any)=>['high','critical'].includes((x.severity||'').toLowerCase())).length}},[d]);
 if(loading)return <main className='analytics-page'><div className='analytics-loading'>{t('Loading Command Center...','جارٍ تحميل مركز القيادة...')}</div></main>;
 const modules=[
  {label:t('Physical Security','الأمن المادي'),value:(d.physical_security_records||[]).length,color:'#2563eb'},
  {label:t('Security Patrols','الدوريات الأمنية'),value:(d.security_patrols||[]).length,color:'#0f766e'},
  {label:t('Agriculture & Landscaping','الزراعة وتنسيق الحدائق'),value:(d.agriculture_checklists||[]).length,color:'#16a34a'},
  {label:t('Assets','الأصول'),value:(d.assets||[]).length,color:'#0891b2'},
  {label:t('Incidents','الحوادث'),value:(d.incidents||[]).length,color:'#dc2626'},
  {label:t('Work Orders','أوامر العمل'),value:(d.work_orders||[]).length,color:'#7c3aed'},
  {label:t('Inspections','التفتيش'),value:(d.inspections||[]).length,color:'#f59e0b'},
  {label:t('Digital Forms','النماذج الرقمية'),value:(d.digital_form_records||[]).length,color:'#6366f1'}
 ];
 const attention=[
  {label:t('Critical / High Risks','المخاطر الحرجة / العالية'),value:s.riskHC,color:'#dc2626'},
  {label:t('Open Corrective Actions','الإجراءات التصحيحية المفتوحة'),value:s.caOpen,color:'#7c3aed'},
  {label:t('Open Emergencies','حالات الطوارئ المفتوحة'),value:s.emgOpen,color:'#ea580c'},
  {label:t('Open Agriculture Follow-ups','متابعات الزراعة المفتوحة'),value:s.fuOpen,color:'#16a34a'}
 ];
 return <main className='analytics-page'>
  <div className='analytics-hero'><div><div className='analytics-eyebrow'>HSS DIGITAL OPERATIONS</div><h1>{t('HSS Executive Command Center','مركز القيادة التنفيذي للصحة والسلامة والأمن')}</h1><p>{t('Live management view across facilities, safety, security, fire, landscaping and field operations','رؤية إدارية مباشرة للمرافق والصحة والسلامة والأمن والسلامة من الحريق والزراعة والعمليات الميدانية')}</p></div><div className='analytics-actions'><a href='/'>{t('Portal','البوابة')}</a><a href='/operations'>{t('Operations','العمليات')}</a><a href='/field-operations'>{t('Field Operations','العمليات الميدانية')}</a><a href='/contracts'>{t('Contracts','العقود')}</a><a href='/ai'>{t('Ask HSS AI','اسأل HSS')}</a><button onClick={()=>setLang(lang==='en'?'ar':'en')}>{lang==='en'?'العربية':'English'}</button></div></div>
  <section className='analytics-kpis'><article className='akpi akpi-red'><span>{t('Open Incidents','الحوادث المفتوحة')}</span><strong>{n(s.incOpen)}</strong><small>{n(s.incCritical)} {t('high / critical','عالية / حرجة')}</small></article><article className='akpi akpi-purple'><span>{t('Open Work Orders','أوامر العمل المفتوحة')}</span><strong>{n(s.woOpen)}</strong><small>{n(s.woOver)} {t('overdue','متأخرة')}</small></article><article className='akpi akpi-blue'><span>{t('Open Risks','المخاطر المفتوحة')}</span><strong>{n(s.riskOpen)}</strong><small>{n(s.riskHC)} {t('high / critical','عالية / حرجة')}</small></article><article className='akpi akpi-green'><span>{t('Open Corrective Actions','الإجراءات التصحيحية المفتوحة')}</span><strong>{n(s.caOpen)}</strong><small>{t('action tracking','متابعة الإجراءات')}</small></article><article className='akpi akpi-cyan'><span>{t('Open Emergencies','حالات الطوارئ المفتوحة')}</span><strong>{n(s.emgOpen)}</strong><small>{n(s.emgCritical)} {t('high / critical','عالية / حرجة')}</small></article></section>
  <section className='analytics-grid'><article className='analytics-card analytics-card-wide'><div className='analytics-card-head'><h2>{t('Operational workload by module','حجم العمل حسب الوحدة')}</h2><p>{t('Live records across the digital portal','السجلات الحية عبر البوابة الرقمية')}</p></div><Bars rows={modules}/></article><article className='analytics-card'><h2>{t('Work Order Compliance','التزام أوامر العمل')}</h2><Donut value={s.woDone} total={(d.work_orders||[]).length} label={t('Completed','مكتمل')} color='#7c3aed'/></article><article className='analytics-card'><h2>{t('Agriculture Compliance','التزام الزراعة')}</h2><Donut value={s.agDone} total={(d.agriculture_checklists||[]).length} label={t('Completed','مكتمل')} color='#16a34a'/></article><article className='analytics-card'><h2>{t('Risk, Emergency & Action Exposure','المخاطر والطوارئ والإجراءات')}</h2><Bars rows={attention}/></article><article className='analytics-card'><h2>{t('Inspection Completion','إنجاز التفتيش')}</h2><Donut value={s.inspDone} total={(d.inspections||[]).length} label={t('Completed','مكتمل')} color='#0891b2'/></article></section>
  <section className='analytics-bottom'><article className='analytics-card'><h2>{t('Management Attention','يتطلب انتباه الإدارة')}</h2><div className='attention-list'><div><span className='dot red'></span><span>{t('Critical / high incidents','الحوادث الحرجة / العالية')}</span><strong>{n(s.incCritical)}</strong></div><div><span className='dot orange'></span><span>{t('Overdue work orders','أوامر العمل المتأخرة')}</span><strong>{n(s.woOver)}</strong></div><div><span className='dot red'></span><span>{t('Critical patrol findings','ملاحظات الدوريات الحرجة')}</span><strong>{n(s.patCritical)}</strong></div><div><span className='dot orange'></span><span>{t('Open emergency events','حالات الطوارئ المفتوحة')}</span><strong>{n(s.emgOpen)}</strong></div><div><span className='dot blue'></span><span>{t('Contracts expiring within 60 days','العقود التي تنتهي خلال ٦٠ يوماً')}</span><strong>{n(s.contracts60)}</strong></div></div></article><article className='analytics-card'><h2>{t('System Status','حالة النظام')}</h2><div className='overview-list'><div><span>{t('User','المستخدم')}</span><strong>{profile?.full_name||profile?.username}</strong></div><div><span>{t('Role','الصلاحية')}</span><strong>{profile?.role}</strong></div><div><span>{t('Database','قاعدة البيانات')}</span><strong>Supabase Live</strong></div><div><span>{t('AI','الذكاء الاصطناعي')}</span><strong>Vercel AI Gateway</strong></div><div><span>{t('Command Center','مركز القيادة')}</span><strong>{t('Operational','تشغيلي')}</strong></div></div></article></section>
 </main>;
}
