'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const supabase=createClient('https://sdbdppcbvlalyjnxeqmy.supabase.co','sb_publishable_YRnoxe5WTODYiA67nLfpNg_JqYHdaYM');

function Donut({value,total,label,color}:{value:number,total:number,label:string,color:string}){const pct=total?Math.round(value/total*100):0;const r=44,c=2*Math.PI*r,dash=c*pct/100;return <div className='viz-donut-wrap'><svg viewBox='0 0 120 120' className='viz-donut'><circle cx='60' cy='60' r={r} className='viz-ring-bg'/><circle cx='60' cy='60' r={r} fill='none' stroke={color} strokeWidth='12' strokeLinecap='round' strokeDasharray={`${dash} ${c-dash}`} transform='rotate(-90 60 60)'/><text x='60' y='57' textAnchor='middle' className='viz-donut-number'>{pct}%</text><text x='60' y='76' textAnchor='middle' className='viz-donut-small'>{value}/{total}</text></svg><div className='viz-donut-label'>{label}</div></div>}
function Bars({rows}:{rows:{label:string,value:number,color:string}[]}){const max=Math.max(1,...rows.map(x=>x.value));return <div className='viz-bars'>{rows.map((r,i)=><div className='viz-bar-row' key={i}><div className='viz-bar-label'><span>{r.label}</span><strong>{r.value}</strong></div><div className='viz-bar-track'><div className='viz-bar-fill' style={{width:`${r.value?Math.max(3,r.value/max*100):0}%`,background:r.color}}/></div></div>)}</div>}

export default function CommandCenter(){
 const [lang,setLang]=useState<'en'|'ar'>('en'),[loading,setLoading]=useState(true),[profile,setProfile]=useState<any>(null),[s,setS]=useState<any>({});
 const t=(en:string,ar:string)=>lang==='ar'?ar:en;const n=(v:any)=>new Intl.NumberFormat(lang==='ar'?'ar-EG':'en-US').format(Number(v||0));
 useEffect(()=>{let active=true;(async()=>{try{const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/');return}const [{data:p},{data:summary,error}]=await Promise.all([supabase.from('profiles').select('username,full_name,role').eq('id',session.user.id).single(),supabase.rpc('hss_dashboard_summary')]);if(!active)return;setProfile(p);if(error)console.error(error);setS(summary||{});}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 useEffect(()=>{document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.documentElement.lang=lang},[lang]);
 if(loading)return <main className='analytics-page'><div className='analytics-loading'>{t('Loading Command Center...','جارٍ تحميل مركز القيادة...')}</div></main>;
 const modules=[
  {label:t('Physical Security','الأمن المادي'),value:s.physical_security_total||0,color:'#2563eb'},
  {label:t('Security Patrols','الدوريات الأمنية'),value:s.security_patrols_total||0,color:'#0f766e'},
  {label:t('Agriculture & Landscaping','الزراعة وتنسيق الحدائق'),value:s.agriculture_total||0,color:'#16a34a'},
  {label:t('Assets','الأصول'),value:s.assets_total||0,color:'#0891b2'},
  {label:t('Incidents','الحوادث'),value:s.incidents_total||0,color:'#dc2626'},
  {label:t('Work Orders','أوامر العمل'),value:s.work_orders_total||0,color:'#7c3aed'},
  {label:t('Inspections','التفتيش'),value:(s.inspections_open||0)+(s.inspections_completed||0),color:'#f59e0b'},
  {label:t('Digital Forms','النماذج الرقمية'),value:s.digital_forms_total||0,color:'#6366f1'}
 ];
 const attention=[
  {label:t('Critical / High Risks','المخاطر الحرجة / العالية'),value:s.risks_high_critical||0,color:'#dc2626'},
  {label:t('Open Corrective Actions','الإجراءات التصحيحية المفتوحة'),value:s.corrective_actions_open||0,color:'#7c3aed'},
  {label:t('Open Emergencies','حالات الطوارئ المفتوحة'),value:s.emergencies_open||0,color:'#ea580c'},
  {label:t('Open Agriculture Follow-ups','متابعات الزراعة المفتوحة'),value:s.agriculture_followups_open||0,color:'#16a34a'}
 ];
 return <main className='analytics-page'>
  <div className='analytics-hero'><div><div className='analytics-eyebrow'>HSS DIGITAL OPERATIONS</div><h1>{t('HSS Executive Command Center','مركز القيادة التنفيذي للصحة والسلامة والأمن')}</h1><p>{t('Live management view across facilities, safety, security, fire, landscaping and field operations','رؤية إدارية مباشرة للمرافق والصحة والسلامة والأمن والسلامة من الحريق والزراعة والعمليات الميدانية')}</p></div><div className='analytics-actions'><a href='/'>{t('Portal','البوابة')}</a><a href='/operations'>{t('Operations','العمليات')}</a><a href='/field-operations'>{t('Field Operations','العمليات الميدانية')}</a><a href='/contracts'>{t('Contracts','العقود')}</a><a href='/ai'>{t('Ask HSS AI','اسأل HSS')}</a><button onClick={()=>setLang(lang==='en'?'ar':'en')}>{lang==='en'?'العربية':'English'}</button></div></div>
  <section className='analytics-kpis'><article className='akpi akpi-red'><span>{t('Open Incidents','الحوادث المفتوحة')}</span><strong>{n(s.incidents_open)}</strong><small>{n(s.incidents_critical)} {t('high / critical','عالية / حرجة')}</small></article><article className='akpi akpi-purple'><span>{t('Open Work Orders','أوامر العمل المفتوحة')}</span><strong>{n(s.work_orders_open)}</strong><small>{n(s.work_orders_overdue)} {t('overdue','متأخرة')}</small></article><article className='akpi akpi-blue'><span>{t('Open Risks','المخاطر المفتوحة')}</span><strong>{n(s.risks_open)}</strong><small>{n(s.risks_high_critical)} {t('high / critical','عالية / حرجة')}</small></article><article className='akpi akpi-green'><span>{t('Open Corrective Actions','الإجراءات التصحيحية المفتوحة')}</span><strong>{n(s.corrective_actions_open)}</strong><small>{t('action tracking','متابعة الإجراءات')}</small></article><article className='akpi akpi-cyan'><span>{t('Open Emergencies','حالات الطوارئ المفتوحة')}</span><strong>{n(s.emergencies_open)}</strong><small>{n(s.emergencies_critical)} {t('high / critical','عالية / حرجة')}</small></article></section>
  <section className='analytics-grid'><article className='analytics-card analytics-card-wide'><div className='analytics-card-head'><h2>{t('Operational workload by module','حجم العمل حسب الوحدة')}</h2><p>{t('Live records across the digital portal','السجلات الحية عبر البوابة الرقمية')}</p></div><Bars rows={modules}/></article><article className='analytics-card'><h2>{t('Agriculture Compliance','التزام الزراعة')}</h2><Donut value={s.agriculture_completed||0} total={s.agriculture_total||0} label={t('Completed','مكتمل')} color='#16a34a'/></article><article className='analytics-card'><h2>{t('Risk, Emergency & Action Exposure','المخاطر والطوارئ والإجراءات')}</h2><Bars rows={attention}/></article><article className='analytics-card'><h2>{t('Inspection Completion','إنجاز التفتيش')}</h2><Donut value={s.inspections_completed||0} total={(s.inspections_completed||0)+(s.inspections_open||0)} label={t('Completed','مكتمل')} color='#0891b2'/></article></section>
  <section className='analytics-bottom'><article className='analytics-card'><h2>{t('Management Attention','يتطلب انتباه الإدارة')}</h2><div className='attention-list'><div><span className='dot red'></span><span>{t('Critical / high incidents','الحوادث الحرجة / العالية')}</span><strong>{n(s.incidents_critical)}</strong></div><div><span className='dot orange'></span><span>{t('Overdue work orders','أوامر العمل المتأخرة')}</span><strong>{n(s.work_orders_overdue)}</strong></div><div><span className='dot red'></span><span>{t('Critical patrol findings','ملاحظات الدوريات الحرجة')}</span><strong>{n(s.security_patrols_high)}</strong></div><div><span className='dot orange'></span><span>{t('Open emergency events','حالات الطوارئ المفتوحة')}</span><strong>{n(s.emergencies_open)}</strong></div><div><span className='dot blue'></span><span>{t('Contracts expiring within 60 days','العقود التي تنتهي خلال ٦٠ يوماً')}</span><strong>{n(s.contracts_expiring_60d)}</strong></div></div></article><article className='analytics-card'><h2>{t('System Status','حالة النظام')}</h2><div className='overview-list'><div><span>{t('User','المستخدم')}</span><strong>{profile?.full_name||profile?.username}</strong></div><div><span>{t('Role','الصلاحية')}</span><strong>{profile?.role}</strong></div><div><span>{t('Database','قاعدة البيانات')}</span><strong>Supabase Live</strong></div><div><span>{t('Command Center','مركز القيادة')}</span><strong>{t('Operational','تشغيلي')}</strong></div></div></article></section>
 </main>;
}