'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

const supabase=createClient('https://sdbdppcbvlalyjnxeqmy.supabase.co','sb_publishable_YRnoxe5WTODYiA67nLfpNg_JqYHdaYM');

export default function Page(){
 const [session,setSession]=useState<any>(null); const [profile,setProfile]=useState<any>(null); const [page,setPage]=useState('dashboard'); const [lang,setLang]=useState<'en'|'ar'>('en'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [incidents,setIncidents]=useState<any[]>([]); const [form,setForm]=useState<any>({category:'Health & Safety',incident_type:'',department:'',building:'',location:'',description:'',severity:'medium',persons_involved:'',injury:false,immediate_action:''});
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session); if(data.session) loadProfile(data.session.user.id)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s); if(s) loadProfile(s.user.id)}); return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.documentElement.lang=lang},[lang]);
 async function loadProfile(id:string){const {data}=await supabase.from('profiles').select('*').eq('id',id).single();setProfile(data);loadIncidents()}
 async function loadIncidents(){const {data}=await supabase.from('incidents').select('*').order('incident_date',{ascending:false});setIncidents(data||[])}
 async function login(){setError('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message)}
 async function signup(){setError('');const {error}=await supabase.auth.signUp({email,password,options:{data:{username:email.split('@')[0],full_name:email.split('@')[0]}}});if(error)setError(error.message)}
 async function logout(){await supabase.auth.signOut();setSession(null);setProfile(null)}
 async function submitIncident(e:any){e.preventDefault();if(!session)return;const {error}=await supabase.from('incidents').insert({...form,status:'reported',approval_status:'pending',reported_by:session.user.id});if(error){alert(error.message);return;}setForm({category:'Health & Safety',incident_type:'',department:'',building:'',location:'',description:'',severity:'medium',persons_involved:'',injury:false,immediate_action:''});await loadIncidents();setPage('incidents')}
 const t=(en:string,ar:string)=>lang==='ar'?ar:en;
 if(!session)return <main className='login'><div className='lang'><button onClick={()=>setLang('en')}>English</button><button onClick={()=>setLang('ar')}>العربية</button></div><section className='card'><div className='brand'>HSS</div><h1>{t('HSS & Facilities Digital Portal','البوابة الرقمية للمرافق والصحة والسلامة والأمن')}</h1><p className='muted'>{t('Health, Safety, Security, Facilities & Landscaping','الصحة والسلامة والأمن والمرافق والزراعة وتنسيق الحدائق')}</p>{error&&<div className='error'>{error}</div>}<div className='form'><input placeholder={t('Email','البريد الإلكتروني')} value={email} onChange={e=>setEmail(e.target.value)}/><input type='password' placeholder={t('Password','كلمة المرور')} value={password} onChange={e=>setPassword(e.target.value)}/><button className='primary' onClick={login}>{t('Login','دخول')}</button><button onClick={signup}>{t('Create first account','إنشاء أول حساب')}</button></div></section></main>;
 const open=incidents.filter(x=>x.status!=='closed').length; const critical=incidents.filter(x=>['high','critical'].includes((x.severity||'').toLowerCase())).length;
 return <div className='shell'><aside className='sidebar'><h2>HSS</h2><button onClick={()=>setPage('dashboard')}>{t('Dashboard','لوحة المعلومات')}</button><button onClick={()=>setPage('incidents')}>{t('Incident Management','إدارة الحوادث')}</button><button onClick={()=>setPage('new')}>{t('New Incident','حادث جديد')}</button><button onClick={logout}>{t('Logout','تسجيل الخروج')}</button></aside><main className='main'><div className='topbar'><span>{profile?.full_name||session.user.email} · {profile?.role}</span><div className='lang'><button onClick={()=>setLang('en')}>EN</button><button onClick={()=>setLang('ar')}>العربية</button></div></div><div className='content'>
 {page==='dashboard'&&<><h1>{t('Management Dashboard','لوحة معلومات الإدارة')}</h1><div className='grid'><div className='card kpi'><div className='label'>{t('Total Incidents','إجمالي الحوادث')}</div><div className='value'>{incidents.length}</div></div><div className='card kpi'><div className='label'>{t('Open Incidents','الحوادث المفتوحة')}</div><div className='value'>{open}</div></div><div className='card kpi'><div className='label'>{t('High / Critical','عالية / حرجة')}</div><div className='value'>{critical}</div></div><div className='card kpi'><div className='label'>{t('User Role','صلاحية المستخدم')}</div><div className='value' style={{fontSize:18}}>{profile?.role}</div></div></div></>}
 {page==='incidents'&&<><div className='actions'><h1 style={{flex:1}}>{t('Incident Management','إدارة الحوادث')}</h1><button className='primary' onClick={()=>setPage('new')}>{t('New Incident','حادث جديد')}</button></div><div className='card' style={{overflowX:'auto'}}><table><thead><tr><th>{t('No.','الرقم')}</th><th>{t('Date','التاريخ')}</th><th>{t('Category','الفئة')}</th><th>{t('Type','النوع')}</th><th>{t('Location','الموقع')}</th><th>{t('Severity','الخطورة')}</th><th>{t('Status','الحالة')}</th></tr></thead><tbody>{incidents.map(i=><tr key={i.id}><td>{i.incident_no}</td><td>{i.incident_date?.slice(0,10)}</td><td>{i.category}</td><td>{i.incident_type}</td><td>{i.building||i.location}</td><td>{i.severity}</td><td>{i.status}</td></tr>)}</tbody></table></div></>}
 {page==='new'&&<><h1>{t('New Incident','تسجيل حادث جديد')}</h1><form className='card form' onSubmit={submitIncident}><div className='row'><div><label>{t('Category','الفئة')}</label><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Health & Safety</option><option>Physical Security</option><option>Fire & Life Safety</option><option>Facilities</option></select></div><div><label>{t('Incident Type','نوع الحادث')}</label><input required value={form.incident_type} onChange={e=>setForm({...form,incident_type:e.target.value})}/></div></div><div className='row'><div><label>{t('Department','الإدارة')}</label><input value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/></div><div><label>{t('Building','المبنى')}</label><input value={form.building} onChange={e=>setForm({...form,building:e.target.value})}/></div></div><div className='row'><div><label>{t('Location','الموقع')}</label><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></div><div><label>{t('Severity','الخطورة')}</label><select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}><option value='low'>Low</option><option value='medium'>Medium</option><option value='high'>High</option><option value='critical'>Critical</option></select></div></div><div><label>{t('Description','وصف الحادث')}</label><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div><label>{t('Persons Involved','الأشخاص المعنيون')}</label><textarea value={form.persons_involved} onChange={e=>setForm({...form,persons_involved:e.target.value})}/></div><label><input style={{width:'auto'}} type='checkbox' checked={form.injury} onChange={e=>setForm({...form,injury:e.target.checked})}/> {t('Injury','إصابة')}</label><div><label>{t('Immediate Action','الإجراء الفوري')}</label><textarea value={form.immediate_action} onChange={e=>setForm({...form,immediate_action:e.target.value})}/></div><button className='primary'>{t('Submit Incident','تسجيل الحادث')}</button></form></>}
 </div></main></div>;
}
