'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

const supabase=createClient('https://sdbdppcbvlalyjnxeqmy.supabase.co','sb_publishable_YRnoxe5WTODYiA67nLfpNg_JqYHdaYM');

const defaultPerms={dashboard:true,physical_security:false,agriculture:false,health_safety:true,facilities:false,ai:true};
const moduleOptions=[['physical_security','Physical Security','الأمن المادي'],['agriculture','Agriculture & Landscaping','الزراعة وتنسيق الحدائق'],['health_safety','Health & Safety','الصحة والسلامة'],['facilities','Facilities Management','إدارة المرافق'],['ai','Ask HSS AI','اسأل مساعد HSS الذكي']];

export default function Page(){
 const [session,setSession]=useState<any>(null),[profile,setProfile]=useState<any>(null),[page,setPage]=useState('dashboard'),[lang,setLang]=useState<'en'|'ar'>('en'),[loading,setLoading]=useState(true);
 const [loginId,setLoginId]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');
 const [newPassword,setNewPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState('');
 const [users,setUsers]=useState<any[]>([]),[incidents,setIncidents]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[actions,setActions]=useState<any[]>([]);
 const [ps,setPs]=useState<any[]>([]),[ag,setAg]=useState<any[]>([]),[wo,setWo]=useState<any[]>([]),[ppm,setPpm]=useState<any[]>([]),[notifications,setNotifications]=useState<any[]>([]),[summary,setSummary]=useState<any>({});
 const [form,setForm]=useState<any>({category:'Health & Safety',incident_type:'',department:'',building:'',location:'',description:'',severity:'medium',persons_involved:'',injury:false,immediate_action:''});
 const [investigation,setInvestigation]=useState(''),[rootCause,setRootCause]=useState(''),[investigator,setInvestigator]=useState('');
 const [ca,setCa]=useState(''),[caUser,setCaUser]=useState(''),[caDue,setCaDue]=useState('');
 const [userForm,setUserForm]=useState<any>({username:'',full_name:'',password:'',role:'staff',department:'HSS',module_permissions:{...defaultPerms}}),[adminMsg,setAdminMsg]=useState('');
 const [psForm,setPsForm]=useState<any>({type:'Task',system:'',sub_system:'',description:'',location:'',area:'',criticality:'Medium',start_date:'',status:'Open',remarks:''});
 const [agForm,setAgForm]=useState<any>({area_type:'indoor',location:'',landscape_category:'Indoor Plants',activity:'Watering',plant_units:'',status:'planned',check_date:'',remarks:'',contractor:''});
 const [woForm,setWoForm]=useState<any>({type:'PPM',module:'physical_security',system:'',asset_id:'',location:'',description:'',priority:'medium',assigned_to:'',due_date:''});
 const [ppmForm,setPpmForm]=useState<any>({module:'physical_security',system:'',sub_system:'',asset_id:'',location:'',description:'',frequency:'monthly',interval_value:1,start_date:'',priority:'medium',sla_hours:24,assigned_to:''});
 const t=(en:string,ar:string)=>lang==='ar'?ar:en,isAdmin=profile?.role==='admin',manager=['admin','management','supervisor'].includes(profile?.role),unrestricted=['admin','management'].includes(profile?.role),can=(key:string)=>!!profile&&(unrestricted||profile.role==='supervisor'||profile.module_permissions?.[key]);
 const num=(v:any)=>new Intl.NumberFormat(lang==='ar'?'ar-EG':'en-US').format(Number(v||0)),date=(v:any)=>v?new Intl.DateTimeFormat(lang==='ar'?'ar-QA':'en-GB').format(new Date(v)):'-';
 const statusLabel=(s:string)=>{const m:any={open:['Open','مفتوح'],assigned:['Assigned','مسند'],in_progress:['In Progress','قيد التنفيذ'],pending_verification:['Pending Verification','بانتظار التحقق'],completed:['Completed','مكتمل'],rejected:['Rejected','مرفوض'],cancelled:['Cancelled','ملغي'],reported:['Reported','تم الإبلاغ'],under_investigation:['Under Investigation','قيد التحقيق'],pending_corrective_actions:['Corrective Actions','إجراءات تصحيحية'],closed:['Closed','مغلق'],planned:['Planned','مخطط']};return m[s]?t(m[s][0],m[s][1]):s};
 const roleName=(r:string)=>({admin:t('Admin','مدير النظام'),management:t('Management','الإدارة'),supervisor:t('Supervisor','مشرف'),staff:t('Staff','موظف'),contractor:t('Contractor','مقاول'),viewer:t('Viewer','مشاهدة فقط')} as any)[r]||r;
 useEffect(()=>{let alive=true;try{const raw=window.localStorage.getItem('sb-sdbdppcbvlalyjnxeqmy-auth-token');const cached=raw?JSON.parse(raw):null;if(cached?.access_token&&cached?.user){setSession(cached);setLoading(false);loadProfile(cached.user.id)}else setLoading(false)}catch{setLoading(false)}supabase.auth.getSession().then(({data})=>{if(!alive)return;setSession(data.session);if(data.session)loadProfile(data.session.user.id);else{setProfile(null);setSummary({})}}).catch(()=>{});const {data:{subscription}}=supabase.auth.onAuthStateChange((e,s)=>{if(!alive)return;setSession(s);setLoading(false);if(e==='SIGNED_IN'&&s)loadProfile(s.user.id);if(e==='SIGNED_OUT'){setProfile(null);setSummary({})}});return()=>{alive=false;subscription.unsubscribe()}},[]);
 useEffect(()=>{document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.documentElement.lang=lang},[lang]);
 async function loadProfile(id:string){const {data,error}=await supabase.rpc('hss_bootstrap');if(!error&&data?.profile){setProfile(data.profile);setSummary(data.summary||{});loadEssential();loadUsers();return}const {data:p}=await supabase.from('profiles').select('*').eq('id',id).single();setProfile(p);supabase.rpc('hss_dashboard_summary').then(({data:sum})=>setSummary(sum||{}));loadEssential();loadUsers()}
 async function loadEssential(){const [i,n]=await Promise.all([supabase.from('incidents').select('*').order('incident_date',{ascending:false}).limit(20),supabase.from('notifications').select('*').order('created_at',{ascending:false}).limit(20)]);setIncidents(i.data||[]);setNotifications(n.data||[])}
 async function loadUsers(){const {data}=await supabase.from('profiles').select('*').order('full_name');setUsers(data||[])}
 async function loadPs(){const {data}=await supabase.from('physical_security_records').select('*').order('start_date',{ascending:false}).limit(100);setPs(data||[])}
 async function loadAg(){const {data}=await supabase.from('agriculture_checklists').select('*').order('check_date',{ascending:false}).limit(100);setAg(data||[])}
 async function loadWo(){const {data}=await supabase.from('work_orders').select('*').order('created_at',{ascending:false}).limit(100);setWo(data||[])}
 async function loadPpm(){const {data}=await supabase.from('ppm_schedules').select('*').order('next_due_date',{ascending:true}).limit(100);setPpm(data||[])}
 async function login(){setError('');const id=loginId.trim(),email=id.includes('@')?id:`${id.toLowerCase()}@hss.local`;const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(t('Invalid username or password','اسم المستخدم أو كلمة المرور غير صحيحة'))}
 async function logout(){await supabase.auth.signOut();setSession(null);setProfile(null);setPage('dashboard')}
 async function changePassword(e:any){e.preventDefault();setError('');if(newPassword.length<10){setError(t('Password must be at least 10 characters','يجب ألا تقل كلمة المرور عن ١٠ أحرف'));return}if(newPassword!==confirmPassword){setError(t('Passwords do not match','كلمتا المرور غير متطابقتين'));return}const {error:uErr}=await supabase.auth.updateUser({password:newPassword});if(uErr){setError(uErr.message);return}const {error:fErr}=await supabase.functions.invoke('admin-users',{body:{action:'complete_password_change'}});if(fErr){setError(fErr.message);return}setNewPassword('');setConfirmPassword('');await loadProfile(session.user.id)}
 async function submitIncident(e:any){e.preventDefault();if(!session)return;const {error}=await supabase.from('incidents').insert({...form,status:'reported',approval_status:'pending',reported_by:session.user.id});if(error){alert(error.message);return}setForm({category:'Health & Safety',incident_type:'',department:'',building:'',location:'',description:'',severity:'medium',persons_involved:'',injury:false,immediate_action:''});await loadEssential();setPage('incidents')}
 async function openIncident(i:any){if(!users.length)await loadUsers();setSelected(i);setInvestigation(i.investigation_summary||'');setRootCause(i.root_cause||'');setInvestigator(i.investigator_id||'');const {data}=await supabase.from('incident_corrective_actions').select('*').eq('incident_id',i.id).order('created_at');setActions(data||[]);setPage('detail')}
 async function saveInvestigation(status?:string){if(!selected)return;const update:any={investigation_summary:investigation,root_cause:rootCause,investigator_id:investigator||null,updated_at:new Date().toISOString()};if(status)update.status=status;if(status==='closed'){update.closed_at=new Date().toISOString();update.approval_status='approved'}const {data,error}=await supabase.from('incidents').update(update).eq('id',selected.id).select().single();if(error){alert(error.message);return}setSelected(data);await loadEssential()}
 async function addCorrective(){if(!selected||!ca.trim())return;const {error}=await supabase.from('incident_corrective_actions').insert({incident_id:selected.id,action:ca,responsible_user_id:caUser||null,due_date:caDue||null,status:'open'});if(error){alert(error.message);return}setCa('');setCaUser('');setCaDue('');const {data}=await supabase.from('incident_corrective_actions').select('*').eq('incident_id',selected.id).order('created_at');setActions(data||[]);if(['reported','under_investigation'].includes(selected.status))await saveInvestigation('pending_corrective_actions')}
 async function closeAction(a:any){const {error}=await supabase.from('incident_corrective_actions').update({status:'completed',verified_by:session.user.id,verified_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',a.id);if(error){alert(error.message);return}const {data}=await supabase.from('incident_corrective_actions').select('*').eq('incident_id',selected.id).order('created_at');setActions(data||[])}
 async function createUser(e:any){e.preventDefault();setAdminMsg('');if(!userForm.username?.trim()){setAdminMsg(t('Username is required','اسم المستخدم مطلوب'));return}if(!userForm.password||userForm.password.length<10){setAdminMsg(t('Temporary password must be at least 10 characters','يجب ألا تقل كلمة المرور المؤقتة عن ١٠ أحرف'));return}const {data,error}=await supabase.functions.invoke('admin-users',{body:{action:'create',...userForm}});if(error||data?.error){let msg=data?.error||error?.message||'Error';if(String(msg).includes('non-2xx'))msg=t('User could not be created. Check that the username is unique and the temporary password is at least 10 characters.','تعذر إنشاء المستخدم. تأكد من أن اسم المستخدم غير مستخدم وأن كلمة المرور المؤقتة لا تقل عن ١٠ أحرف.');setAdminMsg(msg);return}setAdminMsg(t('User created successfully','تم إنشاء المستخدم بنجاح'));setUserForm({username:'',full_name:'',password:'',role:'staff',department:'HSS',module_permissions:{...defaultPerms}});await loadUsers()}
 async function updateUser(id:string,updates:any){setAdminMsg('');const {data,error}=await supabase.functions.invoke('admin-users',{body:{action:'update',id,...updates}});if(error||data?.error){setAdminMsg(data?.error||error?.message||'Error');return}await loadUsers()}
 async function resetPassword(u:any){const p=prompt(t(`Temporary password for ${u.username} (10+ characters)`,`كلمة المرور المؤقتة للمستخدم ${u.username} (١٠ أحرف على الأقل)`));if(!p)return;const {data,error}=await supabase.functions.invoke('admin-users',{body:{action:'reset_password',id:u.id,password:p}});if(error||data?.error){alert(data?.error||error?.message);return}alert(t('Temporary password updated','تم تحديث كلمة المرور المؤقتة'));await loadUsers()}
 async function createPs(e:any){e.preventDefault();const row={...psForm,source_record_key:`MANUAL-${crypto.randomUUID()}`,source_year:new Date().getFullYear(),start_date:psForm.start_date||new Date().toISOString().slice(0,10)};const {error}=await supabase.from('physical_security_records').insert(row);if(error){alert(error.message);return}setPsForm({type:'Task',system:'',sub_system:'',description:'',location:'',area:'',criticality:'Medium',start_date:'',status:'Open',remarks:''});await loadPs()}
 async function createAg(e:any){e.preventDefault();const row={...agForm,source_record_key:`MANUAL-${crypto.randomUUID()}`,plant_units:agForm.plant_units?Number(agForm.plant_units):null,check_date:agForm.check_date||new Date().toISOString().slice(0,10),created_by:session.user.id};const {error}=await supabase.from('agriculture_checklists').insert(row);if(error){alert(error.message);return}setAgForm({area_type:'indoor',location:'',landscape_category:'Indoor Plants',activity:'Watering',plant_units:'',status:'planned',check_date:'',remarks:'',contractor:''});await loadAg()}
 async function createWo(e:any){e.preventDefault();const row={...woForm,assigned_to:woForm.assigned_to||null,due_date:woForm.due_date||null,created_by:session.user.id,workflow_status:woForm.assigned_to?'assigned':'open',checklist:[],evidence_urls:[]};const {error}=await supabase.from('work_orders').insert(row);if(error){alert(error.message);return}setWoForm({type:'PPM',module:'physical_security',system:'',asset_id:'',location:'',description:'',priority:'medium',assigned_to:'',due_date:''});await loadWo()}
 async function updateWo(id:string,status:string){const update:any={workflow_status:status,updated_at:new Date().toISOString()};if(status==='completed'){update.closed_at=new Date().toISOString();update.overdue=false}const {error}=await supabase.from('work_orders').update(update).eq('id',id);if(error){alert(error.message);return}await loadWo()}
 async function createPpm(e:any){e.preventDefault();const row={...ppmForm,interval_value:Number(ppmForm.interval_value||1),sla_hours:Number(ppmForm.sla_hours||24),assigned_to:ppmForm.assigned_to||null,start_date:ppmForm.start_date,next_due_date:ppmForm.start_date,checklist:[],created_by:session.user.id};const {error}=await supabase.from('ppm_schedules').insert(row);if(error){alert(error.message);return}setPpmForm({module:'physical_security',system:'',sub_system:'',asset_id:'',location:'',description:'',frequency:'monthly',interval_value:1,start_date:'',priority:'medium',sla_hours:24,assigned_to:''});await loadPpm()}
 async function markRead(id:string){const {error}=await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id);if(error){alert(error.message);return}await loadEssential()}
 const dashboard=useMemo(()=>({incidentOpen:summary.incidents_open??incidents.filter(x=>x.status!=='closed').length,incidentCritical:summary.incidents_critical??incidents.filter(x=>['high','critical'].includes((x.severity||'').toLowerCase())).length,psHigh:summary.physical_security_high??0,agCompleted:summary.agriculture_completed??0,woOpen:summary.work_orders_open??0,woOverdue:summary.work_orders_overdue??0,ppmActive:summary.ppm_active??0,unread:summary.notifications_unread??notifications.filter(x=>!x.read_at).length}),[summary,incidents,notifications]);
 function go(p:string){setPage(p);if(['admin','workorders','ppm'].includes(p)&&!users.length)loadUsers();if(p==='physical'&&!ps.length)loadPs();if(p==='agriculture'&&!ag.length)loadAg();if(p==='workorders'&&!wo.length)loadWo();if(p==='ppm'&&!ppm.length)loadPpm()}
 if(loading)return <main className='login'><div className='lang'><button onClick={()=>setLang('en')}>English</button><button onClick={()=>setLang('ar')}>العربية</button></div><section className='card'><div className='brand'>HSS</div><h1>{t('HSS & Facilities Digital Portal','البوابة الرقمية للمرافق والصحة والسلامة والأمن')}</h1><p>{t('Connecting securely…','جارٍ الاتصال الآمن…')}</p></section></main>;
 if(!session){if(typeof window!=='undefined')window.location.replace('/');return <main className='login'><div className='lang'><button onClick={()=>setLang('en')}>English</button><button onClick={()=>setLang('ar')}>العربية</button></div><section className='card'><div className='brand'>HSS</div><h1>{t('HSS & Facilities Digital Portal','البوابة الرقمية للمرافق والصحة والسلامة والأمن')}</h1><p>{t('Secure access to operational services, reporting and analytics','دخول آمن للخدمات التشغيلية والتقارير والتحليلات')}</p><input placeholder={t('Username','اسم المستخدم')} value={loginId} onChange={e=>setLoginId(e.target.value)} autoComplete='username'/><input type='password' placeholder={t('Password','كلمة المرور')} value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&login()} autoComplete='current-password'/><button className='primary' onClick={login}>{t('Sign in','تسجيل الدخول')}</button>{error&&<p className='error'>{error}</p>}</section></main>}
 if(profile?.must_change_password)return <main className='login'><section className='card'><h2>{t('Change temporary password','تغيير كلمة المرور المؤقتة')}</h2><form onSubmit={changePassword}><input type='password' value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder={t('New password','كلمة المرور الجديدة')}/><input type='password' value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} placeholder={t('Confirm password','تأكيد كلمة المرور')}/><button className='primary'>{t('Save password','حفظ كلمة المرور')}</button></form>{error&&<p className='error'>{error}</p>}</section></main>;
 return <div className='app'><aside><div className='logo'>HSS</div><div className='user'><b>{profile?.full_name}</b><small>{roleName(profile?.role)}</small></div><nav><button onClick={()=>go('dashboard')}>▦ {t('Dashboard','لوحة المعلومات')}</button><button onClick={()=>go('report')}>＋ {t('Report Incident','الإبلاغ عن حادث')}</button><button onClick={()=>go('incidents')}>⚠ {t('Incidents','الحوادث')}</button>{can('physical_security')&&<button onClick={()=>go('physical')}>◉ {t('Physical Security','الأمن المادي')}</button>}{can('agriculture')&&<button onClick={()=>go('agriculture')}>♣ {t('Agriculture & Landscaping','الزراعة وتنسيق الحدائق')}</button>}{isAdmin&&<button onClick={()=>go('admin')}>♙ {t('User Administration','إدارة المستخدمين')}</button>}<a href='/command-center'>◫ {t('Command Center','مركز القيادة')}</a><a href='/contracts'>▣ {t('Contracts','العقود')}</a><a href='/field-operations'>⌖ {t('Field Operations','العمليات الميدانية')}</a><a href='/ai'>✦ {t('Ask HSS AI','اسأل HSS')}</a></nav><div className='bottom'><button onClick={()=>setLang(lang==='en'?'ar':'en')}>🌐 {lang==='en'?'العربية':'English'}</button><button onClick={logout}>↪ {t('Sign out','تسجيل الخروج')}</button></div></aside><main><header><h1>{t('HSS & Facilities Portal','بوابة المرافق والصحة والسلامة والأمن')}</h1><span>{t('Integrated Digital Operations','العمليات الرقمية المتكاملة')}</span></header>
 {page==='dashboard'&&<section><div className='cards'><Kpi title={t('Open Incidents','الحوادث المفتوحة')} value={num(dashboard.incidentOpen)} sub={`${num(dashboard.incidentCritical)} ${t('high / critical','عالية / حرجة')}`}/><Kpi title={t('Physical Security','الأمن المادي')} value={num(summary.physical_security_total||0)} sub={`${num(dashboard.psHigh)} ${t('high criticality','عالية الأهمية')}`}/><Kpi title={t('Agriculture Completed','الزراعة المكتملة')} value={num(dashboard.agCompleted)} sub={`${num(summary.agriculture_total||0)} ${t('total records','إجمالي السجلات')}`}/><Kpi title={t('Unread Notifications','الإشعارات غير المقروءة')} value={num(dashboard.unread)} sub={t('assigned tasks & alerts','المهام والتنبيهات المسندة')}/></div><div className='panel'><h2>{t('Recent Incidents','أحدث الحوادث')}</h2><IncidentTable rows={incidents.slice(0,8)} open={openIncident} t={t} statusLabel={statusLabel} date={date}/></div></section>}
 {page==='report'&&<section className='panel'><h2>{t('Report New Incident','الإبلاغ عن حادث جديد')}</h2><form onSubmit={submitIncident} className='grid'><Select label={t('Category','الفئة')} value={form.category} set={(v:any)=>setForm({...form,category:v})} opts={['Health & Safety','Physical Security','Facilities Management','Fire & Life Safety']}/><Input label={t('Incident Type','نوع الحادث')} value={form.incident_type} set={(v:any)=>setForm({...form,incident_type:v})}/><Input label={t('Department','الإدارة')} value={form.department} set={(v:any)=>setForm({...form,department:v})}/><Input label={t('Building','المبنى')} value={form.building} set={(v:any)=>setForm({...form,building:v})}/><Input label={t('Location','الموقع')} value={form.location} set={(v:any)=>setForm({...form,location:v})}/><Select label={t('Severity','درجة الخطورة')} value={form.severity} set={(v:any)=>setForm({...form,severity:v})} opts={['low','medium','high','critical']}/><Text label={t('Description','الوصف')} value={form.description} set={(v:any)=>setForm({...form,description:v})}/><Text label={t('Immediate Action','الإجراء الفوري')} value={form.immediate_action} set={(v:any)=>setForm({...form,immediate_action:v})}/><button className='primary'>{t('Submit Incident','إرسال البلاغ')}</button></form></section>}
 {page==='incidents'&&<section className='panel'><h2>{t('Incident Register','سجل الحوادث')}</h2><IncidentTable rows={incidents} open={openIncident} t={t} statusLabel={statusLabel} date={date}/></section>}
 {page==='detail'&&selected&&<section className='panel'><h2>{t('Incident','الحادث')} {selected.incident_number}</h2><p>{selected.description}</p><div className='grid'><Text label={t('Investigation Summary','ملخص التحقيق')} value={investigation} set={setInvestigation}/><Text label={t('Root Cause Analysis','تحليل السبب الجذري')} value={rootCause} set={setRootCause}/>{manager&&<Select label={t('Investigator','المحقق')} value={investigator} set={setInvestigator} opts={users.filter(u=>u.active).map(u=>({value:u.id,label:u.full_name||u.username}))}/>}</div>{manager&&<div className='actions'><button onClick={()=>saveInvestigation('under_investigation')}>{t('Save Investigation','حفظ التحقيق')}</button><button onClick={()=>saveInvestigation('closed')} className='primary'>{t('Approve & Close','اعتماد وإغلاق')}</button></div>}<h3>{t('Corrective Actions','الإجراءات التصحيحية')}</h3>{actions.map(a=><div className='actionrow' key={a.id}><span>{a.action}</span><b>{statusLabel(a.status)}</b>{manager&&a.status!=='completed'&&<button onClick={()=>closeAction(a)}>{t('Verify Complete','التحقق من الإكمال')}</button>}</div>)}{manager&&<div className='grid'><Input label={t('Corrective Action','الإجراء التصحيحي')} value={ca} set={setCa}/><Select label={t('Responsible User','المستخدم المسؤول')} value={caUser} set={setCaUser} opts={users.filter(u=>u.active).map(u=>({value:u.id,label:u.full_name||u.username}))}/><Input label={t('Due Date','تاريخ الاستحقاق')} type='date' value={caDue} set={setCaDue}/><button onClick={addCorrective} className='primary'>{t('Add Action','إضافة إجراء')}</button></div>}</section>}
 {page==='physical'&&<section className='panel'><h2>{t('Physical Security Records','سجلات الأمن المادي')}</h2>{manager&&<form onSubmit={createPs} className='grid'><Select label={t('Type','النوع')} value={psForm.type} set={(v:any)=>setPsForm({...psForm,type:v})} opts={['Task','Project','Corrective','PPM']}/><Input label={t('System','النظام')} value={psForm.system} set={(v:any)=>setPsForm({...psForm,system:v})}/><Input label={t('Sub-system','النظام الفرعي')} value={psForm.sub_system} set={(v:any)=>setPsForm({...psForm,sub_system:v})}/><Input label={t('Location','الموقع')} value={psForm.location} set={(v:any)=>setPsForm({...psForm,location:v})}/><Text label={t('Description','الوصف')} value={psForm.description} set={(v:any)=>setPsForm({...psForm,description:v})}/><button className='primary'>{t('Add Record','إضافة سجل')}</button></form>}<SimpleTable headers={[t('Type','النوع'),t('System','النظام'),t('Description','الوصف'),t('Location','الموقع'),t('Status','الحالة')]} rows={ps.map(x=>[x.type,x.system,x.description,x.location,x.status])}/></section>}
 {page==='agriculture'&&<section className='panel'><h2>{t('Agriculture & Landscaping','الزراعة وتنسيق الحدائق')}</h2>{manager&&<form onSubmit={createAg} className='grid'><Select label={t('Area Type','نوع المنطقة')} value={agForm.area_type} set={(v:any)=>setAgForm({...agForm,area_type:v})} opts={[{value:'indoor',label:t('Indoor','داخلي')},{value:'outdoor',label:t('Outdoor','خارجي')}]}/><Input label={t('Location','الموقع')} value={agForm.location} set={(v:any)=>setAgForm({...agForm,location:v})}/><Input label={t('Activity','النشاط')} value={agForm.activity} set={(v:any)=>setAgForm({...agForm,activity:v})}/><Input label={t('Check Date','تاريخ الفحص')} type='date' value={agForm.check_date} set={(v:any)=>setAgForm({...agForm,check_date:v})}/><Text label={t('Remarks','الملاحظات')} value={agForm.remarks} set={(v:any)=>setAgForm({...agForm,remarks:v})}/><button className='primary'>{t('Add Checklist','إضافة قائمة فحص')}</button></form>}<SimpleTable headers={[t('Area','المنطقة'),t('Location','الموقع'),t('Activity','النشاط'),t('Date','التاريخ'),t('Status','الحالة')]} rows={ag.map(x=>[x.area_type,x.location,x.activity,date(x.check_date),statusLabel(x.status)])}/></section>}
 {page==='workorders'&&<section className='panel'><h2>{t('Work Orders','أوامر العمل')}</h2><form onSubmit={createWo} className='grid'><Select label={t('Type','النوع')} value={woForm.type} set={(v:any)=>setWoForm({...woForm,type:v})} opts={['PPM','Corrective','Inspection','Incident Action']}/><Select label={t('Module','الوحدة')} value={woForm.module} set={(v:any)=>setWoForm({...woForm,module:v})} opts={moduleOptions.map(x=>({value:x[0],label:t(x[1],x[2])}))}/><Input label={t('System','النظام')} value={woForm.system} set={(v:any)=>setWoForm({...woForm,system:v})}/><Input label={t('Location','الموقع')} value={woForm.location} set={(v:any)=>setWoForm({...woForm,location:v})}/><Text label={t('Description','الوصف')} value={woForm.description} set={(v:any)=>setWoForm({...woForm,description:v})}/><Select label={t('Assign To','إسناد إلى')} value={woForm.assigned_to} set={(v:any)=>setWoForm({...woForm,assigned_to:v})} opts={users.filter(u=>u.active).map(u=>({value:u.id,label:u.full_name||u.username}))}/><Input label={t('Due Date','تاريخ الاستحقاق')} type='date' value={woForm.due_date} set={(v:any)=>setWoForm({...woForm,due_date:v})}/><button className='primary'>{t('Create Work Order','إنشاء أمر عمل')}</button></form><SimpleTable headers={[t('WO','أمر العمل'),t('Type','النوع'),t('Description','الوصف'),t('Status','الحالة'),t('Due','الاستحقاق')]} rows={wo.map(x=>[x.work_order_number,x.type,x.description,statusLabel(x.workflow_status),date(x.due_date)])}/></section>}
 {page==='ppm'&&<section className='panel'><h2>{t('PPM Schedules','جداول الصيانة الوقائية')}</h2><form onSubmit={createPpm} className='grid'><Select label={t('Module','الوحدة')} value={ppmForm.module} set={(v:any)=>setPpmForm({...ppmForm,module:v})} opts={moduleOptions.map(x=>({value:x[0],label:t(x[1],x[2])}))}/><Input label={t('System','النظام')} value={ppmForm.system} set={(v:any)=>setPpmForm({...ppmForm,system:v})}/><Text label={t('Description','الوصف')} value={ppmForm.description} set={(v:any)=>setPpmForm({...ppmForm,description:v})}/><Select label={t('Frequency','التكرار')} value={ppmForm.frequency} set={(v:any)=>setPpmForm({...ppmForm,frequency:v})} opts={['daily','weekly','monthly','quarterly','semiannual','annual']}/><Input label={t('Start Date','تاريخ البدء')} type='date' value={ppmForm.start_date} set={(v:any)=>setPpmForm({...ppmForm,start_date:v})}/><Select label={t('Assign To','إسناد إلى')} value={ppmForm.assigned_to} set={(v:any)=>setPpmForm({...ppmForm,assigned_to:v})} opts={users.filter(u=>u.active).map(u=>({value:u.id,label:u.full_name||u.username}))}/><button className='primary'>{t('Create PPM','إنشاء صيانة وقائية')}</button></form><SimpleTable headers={[t('System','النظام'),t('Description','الوصف'),t('Frequency','التكرار'),t('Next Due','الاستحقاق القادم')]} rows={ppm.map(x=>[x.system,x.description,x.frequency,date(x.next_due_date)])}/></section>}
 {page==='admin'&&isAdmin&&<section className='panel'><h2>{t('User Administration','إدارة المستخدمين')}</h2><form onSubmit={createUser} className='grid'><Input label={t('Username','اسم المستخدم')} value={userForm.username} set={(v:any)=>setUserForm({...userForm,username:v})}/><Input label={t('Full Name','الاسم الكامل')} value={userForm.full_name} set={(v:any)=>setUserForm({...userForm,full_name:v})}/><Input label={t('Temporary Password','كلمة المرور المؤقتة')} type='password' value={userForm.password} set={(v:any)=>setUserForm({...userForm,password:v})}/><Select label={t('Role','الصلاحية')} value={userForm.role} set={(v:any)=>setUserForm({...userForm,role:v})} opts={['admin','management','supervisor','staff','contractor','viewer']}/><button className='primary'>{t('Create User','إنشاء مستخدم')}</button></form>{adminMsg&&<p>{adminMsg}</p>}<SimpleTable headers={[t('Name','الاسم'),t('Username','اسم المستخدم'),t('Role','الصلاحية'),t('Status','الحالة')]} rows={users.map(u=>[u.full_name,u.username,roleName(u.role),u.active?t('Active','نشط'):t('Disabled','معطل')])}/></section>}
 </main></div>;
}
function Kpi({title,value,sub}:{title:string,value:any,sub:string}){return <article className='kpi'><span>{title}</span><strong>{value}</strong><small>{sub}</small></article>}
function Input({label,value,set,type='text'}:any){return <label><span>{label}</span><input type={type} value={value||''} onChange={e=>set(e.target.value)}/></label>}
function Text({label,value,set}:any){return <label className='wide'><span>{label}</span><textarea value={value||''} onChange={e=>set(e.target.value)}/></label>}
function Select({label,value,set,opts}:any){return <label><span>{label}</span><select value={value||''} onChange={e=>set(e.target.value)}><option value=''>--</option>{opts.map((o:any,i:number)=>typeof o==='string'?<option key={i} value={o}>{o}</option>:<option key={i} value={o.value}>{o.label}</option>)}</select></label>}
function SimpleTable({headers,rows}:any){return <div className='tablewrap'><table><thead><tr>{headers.map((h:string,i:number)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.map((r:any[],i:number)=><tr key={i}>{r.map((c:any,j:number)=><td key={j}>{c??'-'}</td>)}</tr>)}</tbody></table></div>}
function IncidentTable({rows,open,t,statusLabel,date}:any){return <div className='tablewrap'><table><thead><tr><th>{t('No.','الرقم')}</th><th>{t('Category','الفئة')}</th><th>{t('Location','الموقع')}</th><th>{t('Severity','الخطورة')}</th><th>{t('Status','الحالة')}</th><th>{t('Date','التاريخ')}</th></tr></thead><tbody>{rows.map((i:any)=><tr key={i.id} onClick={()=>open(i)}><td>{i.incident_number}</td><td>{i.category}</td><td>{i.location}</td><td>{i.severity}</td><td>{statusLabel(i.status)}</td><td>{date(i.incident_date)}</td></tr>)}</tbody></table></div>}