'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const supabase=createClient('https://sdbdppcbvlalyjnxeqmy.supabase.co','sb_publishable_YRnoxe5WTODYiA67nLfpNg_JqYHdaYM');
export default function AgriculturePage(){
 const [lang,setLang]=useState<'en'|'ar'>('en'),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState(''),[selected,setSelected]=useState<any>(null);
 const [form,setForm]=useState<any>({area_type:'indoor',location:'',landscape_category:'Indoor Plants',activity:'Watering',plant_units:'',status:'planned',check_date:new Date().toISOString().slice(0,10),remarks:'',contractor:''});
 const t=(en:string,ar:string)=>lang==='ar'?ar:en; const d=(v:any)=>v?new Intl.DateTimeFormat(lang==='ar'?'ar-QA':'en-GB',{dateStyle:'medium'}).format(new Date(v)):'—';
 useEffect(()=>{document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.documentElement.lang=lang;load()},[lang]);
 async function load(){setLoading(true);const {data:{session}}=await supabase.auth.getSession();if(!session){location.replace('/');return}const {data,error}=await supabase.from('agriculture_checklists').select('*').order('check_date',{ascending:false}).order('created_at',{ascending:false});if(error)setMsg(error.message);setRows(data||[]);setLoading(false)}
 async function create(e:any){e.preventDefault();const {data:{user}}=await supabase.auth.getUser();const payload={...form,plant_units:form.plant_units?Number(form.plant_units):null,source_record_key:`MANUAL-${crypto.randomUUID()}`,created_by:user?.id};const {error}=await supabase.from('agriculture_checklists').insert(payload);if(error){setMsg(error.message);return}setMsg(t('Checklist created successfully','تم إنشاء قائمة الفحص بنجاح'));setForm({area_type:'indoor',location:'',landscape_category:'Indoor Plants',activity:'Watering',plant_units:'',status:'planned',check_date:new Date().toISOString().slice(0,10),remarks:'',contractor:''});await load()}
 async function updateStatus(row:any,status:string){const {error}=await supabase.from('agriculture_checklists').update({status}).eq('id',row.id);if(error){setMsg(error.message);return}setMsg(status==='completed'?t('Checklist completed. Dashboard updated.','تم إكمال قائمة الفحص وتحديث لوحة المعلومات.'):t('Checklist status updated','تم تحديث حالة قائمة الفحص'));setSelected(null);await load()}
 async function saveDetails(){if(!selected)return;const {error}=await supabase.from('agriculture_checklists').update({location:selected.location,activity:selected.activity,remarks:selected.remarks||'',contractor:selected.contractor||'',plant_units:selected.plant_units?Number(selected.plant_units):null,check_date:selected.check_date}).eq('id',selected.id);if(error){setMsg(error.message);return}setMsg(t('Checklist details saved','تم حفظ تفاصيل قائمة الفحص'));await load()}
 const completed=rows.filter(x=>String(x.status).toLowerCase()==='completed').length,open=rows.length-completed;
 return <main className='content'>
  <div className='actions'><a className='btn' href='/portal'>{t('Portal','البوابة')}</a><a className='btn' href='/command-center'>{t('Command Center','مركز القيادة')}</a><h1 style={{flex:1,margin:0}}>{t('Agriculture & Landscaping Checklists','قوائم فحص الزراعة وتنسيق الحدائق')}</h1><button className='btn' onClick={()=>setLang(lang==='en'?'ar':'en')}>{lang==='en'?'العربية':'English'}</button></div>
  <div className='grid' style={{marginTop:16}}><div className='card kpi'><div className='label'>{t('Total Checklists','إجمالي قوائم الفحص')}</div><div className='value'>{rows.length}</div></div><div className='card kpi'><div className='label'>{t('Completed','مكتملة')}</div><div className='value'>{completed}</div></div><div className='card kpi'><div className='label'>{t('Open / Planned','مفتوحة / مخططة')}</div><div className='value'>{open}</div></div></div>
  {msg&&<div className='card' style={{marginTop:14}}>{msg}</div>}
  <form className='card form' onSubmit={create} style={{marginTop:14}}><h2>{t('Create Agriculture Checklist','إنشاء قائمة فحص زراعية')}</h2><div className='row'><label>{t('Area Type','نوع المنطقة')}<select value={form.area_type} onChange={e=>setForm({...form,area_type:e.target.value})}><option value='indoor'>{t('Indoor','داخلي')}</option><option value='outdoor'>{t('Outdoor','خارجي')}</option></select></label><label>{t('Location','الموقع')}<input required value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label></div><div className='row'><label>{t('Activity','النشاط')}<input required value={form.activity} onChange={e=>setForm({...form,activity:e.target.value})}/></label><label>{t('Check Date','تاريخ الفحص')}<input type='date' required value={form.check_date} onChange={e=>setForm({...form,check_date:e.target.value})}/></label></div><div className='row'><label>{t('Plant Units','عدد الوحدات النباتية')}<input type='number' min='0' value={form.plant_units} onChange={e=>setForm({...form,plant_units:e.target.value})}/></label><label>{t('Contractor','المقاول')}<input value={form.contractor} onChange={e=>setForm({...form,contractor:e.target.value})}/></label></div><label>{t('Remarks / Findings','الملاحظات / النتائج')}<textarea value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})}/></label><button className='primary'>{t('Create Checklist','إنشاء قائمة الفحص')}</button></form>
  <div className='card' style={{marginTop:14,overflowX:'auto'}}><h2>{t('Checklist Register','سجل قوائم الفحص')}</h2>{loading?<p>{t('Loading...','جارٍ التحميل...')}</p>:<table><thead><tr><th>{t('Location','الموقع')}</th><th>{t('Activity','النشاط')}</th><th>{t('Date','التاريخ')}</th><th>{t('Status','الحالة')}</th><th>{t('Actions','الإجراءات')}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className='drillable' onClick={()=>setSelected({...r})}><td>{r.location}</td><td>{r.activity}</td><td>{d(r.check_date)}</td><td>{tStatus(r.status,t)}</td><td onClick={e=>e.stopPropagation()}><div className='actions'>{r.status==='planned'&&<button onClick={()=>updateStatus(r,'in_progress')}>{t('Start','بدء')}</button>}{r.status!=='completed'&&<button className='primary' onClick={()=>updateStatus(r,'completed')}>{t('Complete','إكمال')}</button>}{r.status==='completed'&&<button onClick={()=>updateStatus(r,'planned')}>{t('Reopen','إعادة فتح')}</button>}</div></td></tr>)}</tbody></table>}</div>
  {selected&&<div className='drill-overlay' onClick={()=>setSelected(null)}><section className='drill-panel' onClick={e=>e.stopPropagation()}><div className='drill-head'><div><small>{t('Checklist Details','تفاصيل قائمة الفحص')}</small><h2>{selected.location}</h2></div><button onClick={()=>setSelected(null)}>×</button></div><div className='form'><label>{t('Location','الموقع')}<input value={selected.location||''} onChange={e=>setSelected({...selected,location:e.target.value})}/></label><label>{t('Activity','النشاط')}<input value={selected.activity||''} onChange={e=>setSelected({...selected,activity:e.target.value})}/></label><label>{t('Check Date','تاريخ الفحص')}<input type='date' value={selected.check_date||''} onChange={e=>setSelected({...selected,check_date:e.target.value})}/></label><label>{t('Plant Units','عدد الوحدات النباتية')}<input type='number' value={selected.plant_units||''} onChange={e=>setSelected({...selected,plant_units:e.target.value})}/></label><label>{t('Contractor','المقاول')}<input value={selected.contractor||''} onChange={e=>setSelected({...selected,contractor:e.target.value})}/></label><label>{t('Remarks / Findings','الملاحظات / النتائج')}<textarea value={selected.remarks||''} onChange={e=>setSelected({...selected,remarks:e.target.value})}/></label><div className='actions'><button onClick={saveDetails}>{t('Save Details','حفظ التفاصيل')}</button>{selected.status!=='completed'&&<button className='primary' onClick={()=>updateStatus(selected,'completed')}>{t('Complete Checklist','إكمال قائمة الفحص')}</button>}{selected.status==='completed'&&<button onClick={()=>updateStatus(selected,'planned')}>{t('Reopen Checklist','إعادة فتح قائمة الفحص')}</button>}</div></div></section></div>}
 </main>
}
function tStatus(v:string,t:(a:string,b:string)=>string){const s=String(v||'').toLowerCase();if(s==='completed')return t('Completed','مكتمل');if(s==='in_progress')return t('In Progress','قيد التنفيذ');if(s==='planned')return t('Planned','مخطط');return v||'—'}
