import {NextResponse} from 'next/server';
import {gunzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';

const SUPABASE_URL='https://sdbdppcbvlalyjnxeqmy.supabase.co';
const SUPABASE_KEY='sb_publishable_YRnoxe5WTODYiA67nLfpNg_JqYHdaYM';
const BASE='https://raw.githubusercontent.com/alizreik-ui/hss-facilities-portal/main/data/ps_csv_parts';
const NAMES=['0.txt','1.txt','1_tail.txt','2.txt','3.txt','4.txt','5.txt'];
async function text(path:string){const r=await fetch(`${BASE}/${path}`,{cache:'no-store'});if(!r.ok)throw new Error(`Unable to load ${path}: ${r.status}`);return (await r.text()).trim()}
function sha(v:string){return createHash('sha256').update(v).digest('hex')}
function parseCSV(s:string){const rows:string[][]=[];let row:string[]=[],v='',q=false;for(let i=0;i<s.length;i++){const c=s[i];if(q){if(c==='"'&&s[i+1]==='"'){v+='"';i++}else if(c==='"')q=false;else v+=c}else{if(c==='"')q=true;else if(c===','){row.push(v);v=''}else if(c==='\n'){row.push(v.replace(/\r$/,''));rows.push(row);row=[];v=''}else v+=c}}if(v||row.length){row.push(v);rows.push(row)}const h=rows.shift()||[];return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((k,i)=>[k.replace(/^\uFEFF/,''),r[i]??''])))}
export async function GET(req:Request){try{const url=new URL(req.url);const token=url.searchParams.get('token');if(!token)return NextResponse.json({error:'Import token required'},{status:401});const parts=await Promise.all(NAMES.map(text));if(url.searchParams.get('debug')==='1')return NextResponse.json({parts:NAMES.map((name,i)=>({name,length:parts[i].length,sha256:sha(parts[i])})),combined:{length:parts.join('').length,sha256:sha(parts.join(''))}});const csv=gunzipSync(Buffer.from(parts.join(''),'base64')).toString('utf8');const ps=parseCSV(csv);if(ps.length!==860)return NextResponse.json({error:`Source verification failed: expected 860, got ${ps.length}`},{status:500});const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/import_hss_historical_data`,{method:'POST',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json'},body:JSON.stringify({p_secret:token,p_ps:ps,p_ag:[]}),cache:'no-store'});const body=await r.text();if(!r.ok)return NextResponse.json({error:'Supabase import failed',details:body},{status:500});return NextResponse.json({ok:true,result:JSON.parse(body),source:{physical_security:ps.length}})}catch(e:any){return NextResponse.json({error:e?.message||'Import failed'},{status:500})}}
