'use client';
import {useEffect,useState} from 'react';
import {getSessionSafely,supabase} from '@/lib/supabase-browser';

type Lang='en'|'ar';
export default function Operations(){
 const [lang,setLang]=useState<Lang>('en');
 const [profile,setProfile]=useState<any>(null);
 const [tab,setTab]=useState('assets');
 const [assets,setAssets]=useState<any[]>([]),[inspections,setInspections]=useState<any[]>([]),[risks,setRisks]=useState<any[]>([]),[actions,setActions]=useState<any[]>([]),[followups,setFollowups]=useState<any[]>([]),[contracts,setContracts]=useState<any[]>([]);
 const [msg,setMsg]=useState('');
 const t=(en:string,ar:string)=>lang==='ar'?ar:en;
 const [asset,setAsset]=useState<any>({asset_code:'',asset_name:'',module:'facilities',system:'',building:'',location:'',criticality:'medium'});
 const [inspection,setInspection]=useState<any>({module:'health_safety',inspection_type:'General Inspection',building:'',location:'',scheduled_date:''});
 const [risk,setRisk]=useState<any>({module:'health_safety',title:'',description:'',building:'',location:'',likelihood:3,impact:3,controls:'',target_date:''});
 const [ca,setCa]=useState<any>({source_type:'other',module:'health_safety',title:'',description:'',priority:'medium',due_date:''});
 const [fu,setFu]=useState<any>({area_type:'indoor',location:'',landscape_category:'Indoor Plants',finding:'',condition:'acceptable',required_action:'',target_date:''});
 useEffect(()=>{document.documentElement.dir=lang==='ar'?'rtl':'ltr';load()},[lang]);
 async function load(){
  const {data:{session}}=await getSessionSafely(); if(!session){location.href='/portal';return}
  const {data:p}=await supabase.from('profiles').select('*').eq('id',session.user.id).single(); setProfile(p);
  const [a,i,r,c,f,ct]=await Promise.all([
   supabase.from('assets').select('*').order('created_at',{ascending:false}).limit(200),
   supabase.from('inspections').select('*').order('created_at',{ascending:false}).limit(200),
   supabase.from('risks').select('*').order('created_at',{ascending:false}).limit(200),
   supabase.from('corrective_actions').select('*').order('created_at',{ascending:false}).limit(200),
   supabase.from('agriculture_followups').select('*').order('created_at',{ascending:false}).limit(200),
   supabase.from('contracts').select('*').order('created_at',{ascending:false}).limit(100)
  ]);
  setAssets(a.data||[]);setInspections(i.data||[]);setRisks(r.data||[]);setActions(c.data||[]);setFollowups(f.data||[]);setContracts(ct.data||[]);
 }
 async function userId(){return (await supabase.auth.getUser()).data.user?.id}
 async function addAsset(e:any){e.preventDefault();const uid=await userId();const {error}=await supabase.from('assets').insert({...asset,created_by:uid});done(error,()=>setAsset({asset_code:'',asset_name:'',module:'facilities',system:'',building:'',location:'',criticality:'medium'}))}
 async function addInspection(e:any){e.preventDefault();const uid=await userId();const {error}=await supabase.from('inspections').insert({...inspection,created_by:uid,status:'planned',checklist:[]});done(error,()=>setInspection({module:'health_safety',inspection_type:'General Inspection',building:'',location:'',scheduled_date:''}))}
 async function addRisk(e:any){e.preventDefault();const uid=await userId();const {error}=await supabase.from('risks').insert({...risk,likelihood:Number(risk.likelihood),impact:Number(risk.impact),created_by:uid,status:'open'});done(error,()=>setRisk({module:'health_safety',title:'',description:'',building:'',location:'',likelihood:3,impact:3,controls:'',target_date:''}))}
 async function addCA(e:any){e.preventDefault();const uid=await userId();const {error}=await supabase.from('corrective_actions').insert({...ca,created_by:uid,status:'open'});done(error,()=>setCa({source_type:'other',module:'health_safety',title:'',description:'',priority:'medium',due_date:''}))}
 async function addFollowup(e:any){e.preventDefault();const uid=await userId();const {error}=await supabase.from('agriculture_followups').insert({...fu,created_by:uid,status:'open'});done(error,()=>setFu({area_type:'indoor',location:'',landscape_category:'Indoor Plants',finding:'',condition:'acceptable',required_action:'',target_date:''}))}
 async function done(error:any,reset:()=>void){if(error){setMsg(error.message);return}setMsg(t('Saved successfully','تم الحفظ بنجاح'));reset();await load()}
 const tabs=[['assets','Assets','الأصول'],['inspections','Inspections','التفتيش'],['risks','Risks','المخاطر'],['actions','Corrective Actions','الإجراءات التصحيحية'],['followups','Agriculture Follow-up','متابعة الزراعة'],['contracts','Contracts','العقود']];
 const moduleOptions=<><option value='physical_security'>{t('Physical Security','الأمن المادي')}</option><option value='health_safety'>{t('Health & Safety','الصحة والسلامة')}</option><option value='facilities'>{t('Facilities','المرافق')}</option><option value='agriculture'>{t('Agriculture','الزراعة')}</option><option value='fire_life_safety'>{t('Fire & Life Safety','السلامة من الحريق')}</option></>;
 return <main className='content'>
  <div className='actions'><a className='btn' href='/portal'>{t('Portal','البوابة')}</a><h1 style={{flex:1}}>{t('Operational Management','إدارة العمليات')}</h1><button onClick={()=>setLang('en')}>EN</button><button onClick={()=>setLang('ar')}>العربية</button></div>
  <p className='muted'>{profile?.full_name} · {profile?.role}</p>
  <div className='actions'>{tabs.map(x=><button className={tab===x[0]?'primary':''} onClick={()=>setTab(x[0])} key={x[0]}>{t(x[1],x[2])}</button>)}</div>{msg&&<p>{msg}</p>}
  {tab==='assets'&&<><h2>{t('Assets','الأصول')}</h2><form className='card form' onSubmit={addAsset}><div className='row'><input required placeholder={t('Asset Code','رمز الأصل')} value={asset.asset_code} onChange={e=>setAsset({...asset,asset_code:e.target.value})}/><input required placeholder={t('Asset Name','اسم الأصل')} value={asset.asset_name} onChange={e=>setAsset({...asset,asset_name:e.target.value})}/></div><div className='row'><select value={asset.module} onChange={e=>setAsset({...asset,module:e.target.value})}>{moduleOptions}</select><input placeholder={t('System','النظام')} value={asset.system} onChange={e=>setAsset({...asset,system:e.target.value})}/></div><div className='row'><input placeholder={t('Building','المبنى')} value={asset.building} onChange={e=>setAsset({...asset,building:e.target.value})}/><input placeholder={t('Location','الموقع')} value={asset.location} onChange={e=>setAsset({...asset,location:e.target.value})}/></div><select value={asset.criticality} onChange={e=>setAsset({...asset,criticality:e.target.value})}><option value='low'>{t('Low','منخفض')}</option><option value='medium'>{t('Medium','متوسط')}</option><option value='high'>{t('High','عالٍ')}</option><option value='critical'>{t('Critical','حرج')}</option></select><button className='primary'>{t('Add Asset','إضافة أصل')}</button></form><Table headers={[t('Code','الرمز'),t('Asset','الأصل'),t('Module','الوحدة'),t('System','النظام'),t('Location','الموقع'),t('Status','الحالة')]} rows={assets.map(x=>[x.asset_code,x.asset_name,x.module,x.system,x.building||x.location,x.status])}/></>}
  {tab==='inspections'&&<><h2>{t('Inspections','التفتيش')}</h2><form className='card form' onSubmit={addInspection}><div className='row'><select value={inspection.module} onChange={e=>setInspection({...inspection,module:e.target.value})}>{moduleOptions}</select><input required placeholder={t('Inspection Type','نوع التفتيش')} value={inspection.inspection_type} onChange={e=>setInspection({...inspection,inspection_type:e.target.value})}/></div><div className='row'><input placeholder={t('Building','المبنى')} value={inspection.building} onChange={e=>setInspection({...inspection,building:e.target.value})}/><input placeholder={t('Location','الموقع')} value={inspection.location} onChange={e=>setInspection({...inspection,location:e.target.value})}/></div><input type='date' value={inspection.scheduled_date} onChange={e=>setInspection({...inspection,scheduled_date:e.target.value})}/><button className='primary'>{t('Schedule Inspection','جدولة التفتيش')}</button></form><Table headers={[t('No.','الرقم'),t('Type','النوع'),t('Module','الوحدة'),t('Location','الموقع'),t('Date','التاريخ'),t('Status','الحالة')]} rows={inspections.map(x=>[x.inspection_no,x.inspection_type,x.module,x.building||x.location,x.scheduled_date,x.status])}/></>}
  {tab==='risks'&&<><h2>{t('Risk Register','سجل المخاطر')}</h2><form className='card form' onSubmit={addRisk}><select value={risk.module} onChange={e=>setRisk({...risk,module:e.target.value})}>{moduleOptions}</select><input required placeholder={t('Risk Title','عنوان الخطر')} value={risk.title} onChange={e=>setRisk({...risk,title:e.target.value})}/><textarea placeholder={t('Description','الوصف')} value={risk.description} onChange={e=>setRisk({...risk,description:e.target.value})}/><div className='row'><input type='number' min='1' max='5' value={risk.likelihood} onChange={e=>setRisk({...risk,likelihood:e.target.value})}/><input type='number' min='1' max='5' value={risk.impact} onChange={e=>setRisk({...risk,impact:e.target.value})}/></div><textarea placeholder={t('Existing Controls','الضوابط الحالية')} value={risk.controls} onChange={e=>setRisk({...risk,controls:e.target.value})}/><input type='date' value={risk.target_date} onChange={e=>setRisk({...risk,target_date:e.target.value})}/><button className='primary'>{t('Register Risk','تسجيل الخطر')}</button></form><Table headers={[t('No.','الرقم'),t('Risk','الخطر'),t('Score','الدرجة'),t('Level','المستوى'),t('Owner','المسؤول'),t('Status','الحالة')]} rows={risks.map(x=>[x.risk_no,x.title,x.risk_score,x.risk_level,x.owner_id||'-',x.status])}/></>}
  {tab==='actions'&&<><h2>{t('Corrective Actions','الإجراءات التصحيحية')}</h2><form className='card form' onSubmit={addCA}><div className='row'><select value={ca.module} onChange={e=>setCa({...ca,module:e.target.value})}>{moduleOptions}</select><select value={ca.priority} onChange={e=>setCa({...ca,priority:e.target.value})}><option value='low'>Low</option><option value='medium'>Medium</option><option value='high'>High</option><option value='critical'>Critical</option></select></div><input required placeholder={t('Action Title','عنوان الإجراء')} value={ca.title} onChange={e=>setCa({...ca,title:e.target.value})}/><textarea placeholder={t('Description','الوصف')} value={ca.description} onChange={e=>setCa({...ca,description:e.target.value})}/><input type='date' value={ca.due_date} onChange={e=>setCa({...ca,due_date:e.target.value})}/><button className='primary'>{t('Create Action','إنشاء إجراء')}</button></form><Table headers={[t('No.','الرقم'),t('Action','الإجراء'),t('Module','الوحدة'),t('Priority','الأولوية'),t('Due','الاستحقاق'),t('Status','الحالة')]} rows={actions.map(x=>[x.action_no,x.title,x.module,x.priority,x.due_date,x.status])}/></>}
  {tab==='followups'&&<><h2>{t('Agriculture Follow-up','متابعة الزراعة وتنسيق الحدائق')}</h2><form className='card form' onSubmit={addFollowup}><div className='row'><select value={fu.area_type} onChange={e=>setFu({...fu,area_type:e.target.value})}><option value='indoor'>{t('Indoor','داخلي')}</option><option value='outdoor'>{t('Outdoor','خارجي')}</option></select><input required placeholder={t('Location','الموقع')} value={fu.location} onChange={e=>setFu({...fu,location:e.target.value})}/></div><input placeholder={t('Landscape Category','فئة الزراعة وتنسيق الحدائق')} value={fu.landscape_category} onChange={e=>setFu({...fu,landscape_category:e.target.value})}/><textarea required placeholder={t('Finding','الملاحظة')} value={fu.finding} onChange={e=>setFu({...fu,finding:e.target.value})}/><textarea placeholder={t('Required Action','الإجراء المطلوب')} value={fu.required_action} onChange={e=>setFu({...fu,required_action:e.target.value})}/><div className='row'><select value={fu.condition} onChange={e=>setFu({...fu,condition:e.target.value})}><option value='good'>{t('Good','جيد')}</option><option value='acceptable'>{t('Acceptable','مقبول')}</option><option value='poor'>{t('Poor','ضعيف')}</option><option value='critical'>{t('Critical','حرج')}</option></select><input type='date' value={fu.target_date} onChange={e=>setFu({...fu,target_date:e.target.value})}/></div><button className='primary'>{t('Add Follow-up','إضافة متابعة')}</button></form><Table headers={[t('No.','الرقم'),t('Area','المنطقة'),t('Location','الموقع'),t('Finding','الملاحظة'),t('Target','الموعد'),t('Status','الحالة')]} rows={followups.map(x=>[x.followup_no,x.area_type,x.location,x.finding,x.target_date,x.status])}/></>}
  {tab==='contracts'&&<><h2>{t('Contracts','العقود')}</h2><Table headers={[t('Contract','العقد'),t('Title','العنوان'),t('Module','الوحدة'),t('Start','البداية'),t('End','النهاية'),t('Status','الحالة')]} rows={contracts.map(x=>[x.contract_no,x.title,x.module,x.start_date,x.end_date,x.status])}/><p className='muted'>{t('Contract creation is restricted to Admin and Management.','إنشاء العقود محصور بمدير النظام والإدارة.')}</p></>}
 </main>
}
function Table({headers,rows}:{headers:any[],rows:any[][]}){return <div className='card' style={{overflowX:'auto',marginTop:14}}><table><thead><tr>{headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v??'-'}</td>)}</tr>)}</tbody></table></div>}
