'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const supabase=createClient('https://sdbdppcbvlalyjnxeqmy.supabase.co','sb_publishable_YRnoxe5WTODYiA67nLfpNg_JqYHdaYM');
type Lang='en'|'ar';
export default function FieldOperations(){
 const [lang,setLang]=useState<Lang>('en'),[tab,setTab]=useState('patrols'),[profile,setProfile]=useState<any>(null),[users,setUsers]=useState<any[]>([]),[patrols,setPatrols]=useState<any[]>([]),[emergencies,setEmergencies]=useState<any[]>([]),[forms,setForms]=useState<any[]>([]),[msg,setMsg]=useState('');
 const [patrol,setPatrol]=useState<any>({patrol_type:'routine',building:'',area:'',route:'',officer_name:'',findings:'',action_taken:'',severity:'low'});
 const [emg,setEmg]=useState<any>({emergency_type:'',building:'',location:'',severity:'medium',description:'',crisis_committee_direction:'',action_taken:'',evacuation_required:false,shelter_required:false});
 const [form,setForm]=useState<any>({form_type:'employee_without_id',module:'physical_security',title:'',building:'',location:'',assigned_to:'',details:''});
 const t=(en:string,ar:string)=>lang==='ar'?ar:en; const d=(v:any)=>v?new Intl.DateTimeFormat(lang==='ar'?'ar-QA':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'-';
 const n=(v:any)=>new Intl.NumberFormat(lang==='ar'?'ar-EG':'en-US').format(Number(v||0));
 useEffect(()=>{document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.documentElement.lang=lang;load()},[lang]);
 async function load(){const {data:{session}}=await supabase.auth.getSession();if(!session){location.href='/portal';return}const [p,u,a,b,c]=await Promise.all([supabase.from('profiles').select('*').eq('id',session.user.id).single(),supabase.from('profiles').select('id,full_name,active').eq('active',true).order('full_name'),supabase.from('security_patrols').select('*').order('patrol_date',{ascending:false}).limit(200),supabase.from('emergency_events').select('*').order('event_date',{ascending:false}).limit(200),supabase.from('digital_form_records').select('*').order('created_at',{ascending:false}).limit(200)]);setProfile(p.data);setUsers(u.data||[]);setPatrols(a.data||[]);setEmergencies(b.data||[]);setForms(c.data||[])}
 async function uid(){return (await supabase.auth.getUser()).data.user?.id}
 async function addPatrol(e:any){e.preventDefault();const id=await uid();const {error}=await supabase.from('security_patrols').insert({...patrol,created_by:id,status:'completed',completed_at:new Date().toISOString()});done(error,()=>setPatrol({patrol_type:'routine',building:'',area:'',route:'',officer_name:'',findings:'',action_taken:'',severity:'low'}))}
 async function addEmergency(e:any){e.preventDefault();const id=await uid();const {error}=await supabase.from('emergency_events').insert({...emg,reported_by:id,status:'open'});done(error,()=>setEmg({emergency_type:'',building:'',location:'',severity:'medium',description:'',crisis_committee_direction:'',action_taken:'',evacuation_required:false,shelter_required:false}))}
 async function addForm(e:any){e.preventDefault();const id=await uid();const {error}=await supabase.from('digital_form_records').insert({form_type:form.form_type,module:form.module,title:form.title||formType(form.form_type,t),building:form.building||null,location:form.location||null,assigned_to:form.assigned_to||null,payload:{details:form.details},status:'submitted',submitted_by:id});done(error,()=>setForm({form_type:'employee_without_id',module:'physical_security',title:'',building:'',location:'',assigned_to:'',details:''}))}
 async function done(error:any,reset:()=>void){if(error){setMsg(error.message);return}setMsg(t('Saved successfully','تم الحفظ بنجاح'));reset();await load()}
 return <main className='content'><div className='actions' style={{alignItems:'center'}}><a className='btn' href='/portal'>{t('Portal','البوابة')}</a><a className='btn' href='/command-center'>{t('Command Center','مركز القيادة')}</a><h1 style={{flex:1,margin:0}}>{t('Field Operations & Digital Forms','العمليات الميدانية والنماذج الرقمية')}</h1><div className='lang'><button onClick={()=>setLang('en')}>EN</button><button onClick={()=>setLang('ar')}>العربية</button></div></div>
 <div className='grid' style={{marginTop:14}}><div className='card kpi'><div className='label'>{t('Patrol Records','سجلات الدوريات')}</div><div className='value'>{n(patrols.length)}</div></div><div className='card kpi'><div className='label'>{t('Open Emergencies','حالات الطوارئ المفتوحة')}</div><div className='value'>{n(emergencies.filter(x=>x.status!=='closed').length)}</div></div><div className='card kpi'><div className='label'>{t('Digital Forms','النماذج الرقمية')}</div><div className='value'>{n(forms.length)}</div></div><div className='card kpi'><div className='label'>{t('User Role','صلاحية المستخدم')}</div><div className='value' style={{fontSize:18}}>{profile?.role||'-'}</div></div></div>
 <div className='actions' style={{margin:'14px 0'}}><button className={tab==='patrols'?'primary':''} onClick={()=>setTab('patrols')}>{t('Security Patrols','الدوريات الأمنية')}</button><button className={tab==='emergency'?'primary':''} onClick={()=>setTab('emergency')}>{t('Emergency Management','إدارة الطوارئ')}</button><button className={tab==='forms'?'primary':''} onClick={()=>setTab('forms')}>{t('Digital Forms','النماذج الرقمية')}</button></div>{msg&&<div className='card'>{msg}</div>}
 {tab==='patrols'&&<><form className='card form' onSubmit={addPatrol}><h2>{t('New Patrol Report','تقرير دورية جديد')}</h2><div className='row'><select value={patrol.patrol_type} onChange={e=>setPatrol({...patrol,patrol_type:e.target.value})}><option value='routine'>{t('Routine Patrol','دورية اعتيادية')}</option><option value='focused'>{t('Focused Patrol','دورية موجهة')}</option><option value='emergency'>{t('Emergency Patrol','دورية طارئة')}</option></select><input required placeholder={t('Officer Name','اسم رجل الأمن')} value={patrol.officer_name} onChange={e=>setPatrol({...patrol,officer_name:e.target.value})}/></div><div className='row'><input placeholder={t('Building','المبنى')} value={patrol.building} onChange={e=>setPatrol({...patrol,building:e.target.value})}/><input placeholder={t('Area','المنطقة')} value={patrol.area} onChange={e=>setPatrol({...patrol,area:e.target.value})}/></div><input placeholder={t('Patrol Route','مسار الدورية')} value={patrol.route} onChange={e=>setPatrol({...patrol,route:e.target.value})}/><select value={patrol.severity} onChange={e=>setPatrol({...patrol,severity:e.target.value})}><option value='low'>{t('Low','منخفض')}</option><option value='medium'>{t('Medium','متوسط')}</option><option value='high'>{t('High','عالٍ')}</option><option value='critical'>{t('Critical','حرج')}</option></select><textarea placeholder={t('Findings / Observations','النتائج / الملاحظات')} value={patrol.findings} onChange={e=>setPatrol({...patrol,findings:e.target.value})}/><textarea placeholder={t('Action Taken','الإجراء المتخذ')} value={patrol.action_taken} onChange={e=>setPatrol({...patrol,action_taken:e.target.value})}/><button className='primary'>{t('Submit Patrol Report','حفظ تقرير الدورية')}</button></form><Table heads={[t('No.','الرقم'),t('Date','التاريخ'),t('Officer','رجل الأمن'),t('Building','المبنى'),t('Area','المنطقة'),t('Severity','الخطورة'),t('Status','الحالة')]} rows={patrols.map(x=>[x.patrol_no,d(x.patrol_date),x.officer_name,x.building,x.area,x.severity,x.status])}/></>}
 {tab==='emergency'&&<><form className='card form' onSubmit={addEmergency}><h2>{t('Register Emergency Event','تسجيل حالة طوارئ')}</h2><div className='row'><input required placeholder={t('Emergency Type','نوع الطوارئ')} value={emg.emergency_type} onChange={e=>setEmg({...emg,emergency_type:e.target.value})}/><select value={emg.severity} onChange={e=>setEmg({...emg,severity:e.target.value})}><option value='low'>{t('Low','منخفض')}</option><option value='medium'>{t('Medium','متوسط')}</option><option value='high'>{t('High','عالٍ')}</option><option value='critical'>{t('Critical','حرج')}</option></select></div><div className='row'><input placeholder={t('Building','المبنى')} value={emg.building} onChange={e=>setEmg({...emg,building:e.target.value})}/><input placeholder={t('Location','الموقع')} value={emg.location} onChange={e=>setEmg({...emg,location:e.target.value})}/></div><textarea required placeholder={t('Description','الوصف')} value={emg.description} onChange={e=>setEmg({...emg,description:e.target.value})}/><textarea placeholder={t('Crisis Committee Direction','توجيه لجنة الأزمات')} value={emg.crisis_committee_direction} onChange={e=>setEmg({...emg,crisis_committee_direction:e.target.value})}/><textarea placeholder={t('Action Taken','الإجراء المتخذ')} value={emg.action_taken} onChange={e=>setEmg({...emg,action_taken:e.target.value})}/><div className='row'><label style={{color:'#222'}}><input style={{width:'auto'}} type='checkbox' checked={emg.evacuation_required} onChange={e=>setEmg({...emg,evacuation_required:e.target.checked})}/> {t('Evacuation Required','يتطلب إخلاء')}</label><label style={{color:'#222'}}><input style={{width:'auto'}} type='checkbox' checked={emg.shelter_required} onChange={e=>setEmg({...emg,shelter_required:e.target.checked})}/> {t('Shelter / Stay Inside','البقاء في منطقة التجمع الآمنة / داخل المبنى')}</label></div><button className='primary'>{t('Register Emergency','تسجيل الطوارئ')}</button></form><Table heads={[t('No.','الرقم'),t('Date','التاريخ'),t('Type','النوع'),t('Location','الموقع'),t('Severity','الخطورة'),t('Status','الحالة')]} rows={emergencies.map(x=>[x.emergency_no,d(x.event_date),x.emergency_type,x.building||x.location,x.severity,x.status])}/></>}
 {tab==='forms'&&<><form className='card form' onSubmit={addForm}><h2>{t('Submit Digital Form','تقديم نموذج رقمي')}</h2><div className='row'><select value={form.form_type} onChange={e=>setForm({...form,form_type:e.target.value})}>{FORM_TYPES.map(x=><option key={x[0]} value={x[0]}>{t(x[1],x[2])}</option>)}</select><select value={form.module} onChange={e=>setForm({...form,module:e.target.value})}><option value='physical_security'>{t('Physical Security','الأمن المادي')}</option><option value='health_safety'>{t('Health & Safety','الصحة والسلامة')}</option><option value='fire_life_safety'>{t('Fire & Life Safety','السلامة من الحريق وحماية الأرواح')}</option><option value='facilities'>{t('Facilities','المرافق')}</option></select></div><input placeholder={t('Form Title (optional)','عنوان النموذج (اختياري)')} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><div className='row'><input placeholder={t('Building','المبنى')} value={form.building} onChange={e=>setForm({...form,building:e.target.value})}/><input placeholder={t('Location','الموقع')} value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></div><select value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})}><option value=''>{t('No Assignee','بدون مسؤول محدد')}</option>{users.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select><textarea required placeholder={t('Form Details','تفاصيل النموذج')} value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/><button className='primary'>{t('Submit Form','إرسال النموذج')}</button></form><Table heads={[t('No.','الرقم'),t('Type','النوع'),t('Title','العنوان'),t('Module','الوحدة'),t('Location','الموقع'),t('Status','الحالة'),t('Date','التاريخ')]} rows={forms.map(x=>[x.form_no,formType(x.form_type,t),x.title,x.module,x.building||x.location,x.status,d(x.created_at)])}/></>}
 </main>
}
const FORM_TYPES=[['employee_without_id','Employee Without ID Card','موظف بدون بطاقة تعريف'],['office_key_handover','Office / Room Key Handover','تسليم واستلام مفاتيح المكاتب والغرف'],['patrol_vehicle_key','Patrol Vehicle Key Handover','تسليم واستلام مفتاح مركبة الدورية الأمنية'],['security_shift_handover','Security Shift Handover','تسليم واستلام المناوبة الأمنية'],['lost_found','Lost & Found','المفقودات والموجودات'],['fire_system_check','Fire System Inspection / Maintenance','فحص وصيانة أنظمة الحريق'],['equipment_handover','Equipment Handover','تسليم واستلام المعدات'],['security_occurrence','Security Occurrence / Observation','تسجيل الوقائع والملاحظات الأمنية'],['traffic_violation','Traffic Violation','مخالفات المرور']];
function formType(v:string,t:(a:string,b:string)=>string){const x=FORM_TYPES.find(z=>z[0]===v);return x?t(x[1],x[2]):v}
function Table({heads,rows}:{heads:string[],rows:any[][]}){return <div className='card' style={{marginTop:14,overflowX:'auto'}}><table><thead><tr>{heads.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v??'-'}</td>)}</tr>)}</tbody></table></div>}
